services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zupreme-restaurant-api
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=web'

      - 'traefik.http.routers.zupreme-restaurant-api.rule=Host(`zupreme-restaurant-api.sarasjodin.se`)'
      - 'traefik.http.routers.zupreme-restaurant-api.entrypoints=websecure'
      - 'traefik.http.routers.zupreme-restaurant-api.tls=true'
      - 'traefik.http.routers.zupreme-restaurant-api.tls.certresolver=myresolver'

      - 'traefik.http.routers.zupreme-restaurant-api.service=zupreme-restaurant-api'
      - 'traefik.http.services.zupreme-restaurant-api.loadbalancer.server.port=3000'
    command: npm start
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - web
      - zupreme-restaurant

  mysql:
    image: mysql:8.0
    container_name: zupreme-restaurant-mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - zupreme_restaurant_mysql_data:/var/lib/mysql
      - ./database/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./database/02-seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
    networks:
      - zupreme-restaurant
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD --silent',
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  zupreme_restaurant_mysql_data:

networks:
  web:
    external: true

  zupreme-restaurant:
    driver: bridge
